### PR TITLE
Various UI cleanup

### LINKED ISSUE #87: Indicators for work being done
Anytime a button is pressed that triggers something to be done, or the website is fetching data indicate so. This is already implemented in some places of the website, but this ticket is to have it done wherever possible to provide a better user experience.

### Basic example

When clicking submit button on practice problems, a loader appears until the problem is submitted.

### Motivation

User Experience

### LINKED ISSUE #93: Back button functionality not working as intended for Admin Clarifications
## Description

Back button on a clarification in the Admin side of Abacus uses `history.goBack`  which is not where we want to go back to. We want the user to return to the parent page (Clarifications table).

### Steps to reproduce

* Create a new clarification on the Admin side from a different page than the clarifications page (Submissions, Users, etc.).
* After creation, the user should be brought to a view of the specific clarification
* Click the "Back" button and user should be brought back to wherever they opened the clarification.

### Expected result

The user should be brought back to the original Clarifications table.

### Actual result

The user is returned to the last page the visited (similar to how a back button works in a web browser).

### Other notes

I understand this is how the `goBack()` function works, so it is not so much unexpected functionality as it is a misunderstanding of how the function performs by the developer (me).

### LINKED ISSUE #96: Consistent UI for button placement & page vs modals
## Summary

I would like consistent placement of buttons for the UI as well as consistent decisions for modals vs pages. 

### Basic example

If all buttons throughout the platform are located in the top right corner, check and adapt where buttons do not fit this rule.
Figure out where we are wanting to use modals and where we are wanting to use pages.

### Motivation

To create and maintain a consistent feeling throughout the platform as well as adhering to best UI practices.

### LINKED ISSUE #129: Blue Template Download Button
## Summary

Change download for Blue Template files to match the way it is handled with scratch.

### Motivation

Creates style and UI unity.

### PR DESCRIPTION
**Pull request by brad-cooley**
# Description

## Back Button Functionality 🐞
Added (and fixed) back button functionality for the admin dashboard. Also:
* ➕ Added breadcrumbs for user pages for navigation ease
* ➕ Added cancel buttons where applicable for navigation

Fixes #93 

## Standardized Button & Modal Use 💡
Standardized all button placement to `float right`. Also, checked use cases for Modals vs whole pages. Did not find any changes were needed here.

Fixes #96 
Fixes #129 

## Button Loading Indicators 💡
Gave every button (with the exception of those whose operations are too short to benefit from) a loading and disabled state to indicate work being done.

_Note: `ProblemDescription` save button was not updated as there are questions on how to pass states in that manner._

Fixes #87 

## Began Standardizing Code Syntax & Practices 🧹
Worked with type standardization within syntax. For example:

`const [isLoading, setLoading] = useState<boolean>(true)`
became
`const [isLoading, setLoading] = useState(true)`

Started to work on #55, but not done until syntax is standardized. Would require a stricter linting process.

## Clarification UI Update 💡
Updated the UI of clarifications for Admins. Allows them to see info about the user as well as their most recent submissions.

No issue or feature request for this :(

## Other Minor UI Updates 💡
Other small UI updates here and there (padding, alignment, table rows for no submissions, etc.)

No issue or feature request for this either :( x2

## Type of change

- [x] 🐞 Bug fix

- [x] 💡 New feature

- [x] 🧹 Code Cleanup

  
# How Has This Been Tested?

- [x] Tested individually.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] My changes do not break any features.

### CODE REVIEW

File: frontend/src/pages/gold/Submissions.tsx [hunk 1]
```diff
@@ -63,7 +63,9 @@ const Submissions = (): JSX.Element => {
               </Table.Row>
             ))) : (
               <Table.Row>
-                <Table.Cell colSpan={'100%'}>No Submissions</Table.Cell>
+                <Table.Cell colSpan={'100%'}>
+                  You don&lsquo;t have any submissions yet. Go write some code!
```
Comment (Jl5her) [inline frontend/src/pages/gold/Submissions.tsx:67]: Is the Gold division writing code?

File: frontend/src/components/Login.tsx [hunk 2]
```diff
@@ -33,6 +35,7 @@ const LoginModal = ({ trigger, open }: LoginModalProps): JSX.Element => {
         const { accessToken, ...user } = await response.json()
         localStorage.setItem('accessToken', accessToken)
         setUser(user)
+        setLoggingIn(false)
```
Comment (Jl5her) [inline frontend/src/components/Login.tsx:38]: You only need one setState false. The code after history. ush still runs. For the happy path, setState will be called twice

File: frontend/src/pages/admin/Clarification.tsx [hunk 3]
```diff
@@ -75,8 +94,10 @@ const ClarificationPage = (): JSX.Element => {
       body: JSON.stringify({ cid: clarification.cid, open })
     })
     if (response.ok) {
+      setChangingState(false)
```
Comment (Jl5her) [inline frontend/src/pages/admin/Clarification.tsx:97]: Here aswell

File: frontend/src/pages/admin/submissions/Submission.tsx [hunk 4]
```diff
@@ -49,8 +51,10 @@ const submission = (): JSX.Element => {
       body: JSON.stringify({ sid: submission.sid })
     })
     if (response.ok) {
+      setDeleting(false)
```
Comment (Jl5her) [inline frontend/src/pages/admin/submissions/Submission.tsx:54]: And here

File: frontend/src/pages/admin/Clarification.tsx [hunk 5]
```diff
@@ -56,7 +74,7 @@ const ClarificationPage = (): JSX.Element => {
 
     if (response.ok) {
       await loadClarification()
-      setReplyLoading(false)
+      setReplying(false)
```
Comment (Jl5her) [inline frontend/src/pages/admin/Clarification.tsx:77]: Missing one outside of response.ok here. This setState could probably be moved outside the if statement

**Review by Jl5her — CHANGES_REQUESTED** [review]

**Comment by Jl5her** [comment]
In reference to
> Note: ProblemDescription save button was not updated as there are questions on how to pass states in that manner.

Since the `handleSubmit` functions are all asynchronous:
https://github.com/acm-mu/abacus/blob/cff12784d4ab06dbbfb9cc73dcf1c849c7431f35/frontend/src/pages/admin/problems/NewProblem.tsx#L14
https://github.com/acm-mu/abacus/blob/cff12784d4ab06dbbfb9cc73dcf1c849c7431f35/frontend/src/pages/admin/problems/EditProblem.tsx#L41

The return type of `handleSubmit` can be changed to `Promise<void>` here, 
https://github.com/acm-mu/abacus/blob/cff12784d4ab06dbbfb9cc73dcf1c849c7431f35/frontend/src/components/editor/ProblemEditor.tsx#L12-L15

This allows after calling the `handleSubmit` function to use a `.then` to execute code after the handler has finished like so,

```javascript
setSaveLoading(true)
handleSubmit(problem)
  .then(() => setSaveLoading(false)
```

It may be better at that point to put this in a function called by the JSX than squeeze it into the `onClick` of the Button

**Review by Jl5her — APPROVED** [review]
