### PR TITLE
Socket io types

### LINKED ISSUE #207: typeof error relating to Socket
## Description

- TypeScript error in /app/src/context/socket.ts(4,37):
'Socket' refers to a value, but is being used as a type here. Did you mean 'typeof Socket'?  TS2749

### Steps to reproduce

load Abacus

### Expected result

Abacus should compile

### Actual result

Abacus won't

### Evidence
 - TypeScript error in /app/src/context/socket.ts(4,37):
'Socket' refers to a value, but is being used as a type here. Did you mean 'typeof Socket'?  TS2749

### PR DESCRIPTION
**Pull request by Jl5her**
# Description

* Following Socket.io's [Migrating from 3.x to 4.0](https://socket.io/docs/v4/migrating-from-3-x-to-4-0/#typed-events) guide, defined client to server events on the frontend to conform to the socket io type definition.
* Upgraded tsconfig target to `es6` (`es5` does not have `class` keyword, which `Socket` is, so compilation error that `Socket` is not a type is because babel transpiles it down to a `function`)

Fixes #207 

## Type of change

- [x] 🐞 Bug fix

  
# How Has This Been Tested?

- [x] Tested individually.
* Compiles to build, and runs locally

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] My changes do not break any features.

### CODE REVIEW

File: frontend/src/context/socket.ts [hunk 1]
```diff
@@ -1,6 +1,17 @@
...
+  notification: (notification: Notification) => void
+  new_submission: (submission: Submission) => void
+  update_submission: (submission: Submission) => void
+  delete_submission: (submission: Submission) => void
+}
+
+// eslint-disable-next-line @typescript-eslint/no-empty-interface
+interface ServerToClientEvents {}
+
+const SocketContext = createContext<Socket<ClientToServerEvents, ServerToClientEvents> | undefined>(undefined)
```
Comment (MrKevinOConnell) [inline frontend/src/context/socket.ts:15]: lmao, that makes a lot more sense now why the errors were throwing

File: frontend/tsconfig.json [hunk 2]
```diff
@@ -1,21 +1,21 @@
...
-        "moduleResolution": "node",
-        "resolveJsonModule": true,
-        "isolatedModules": true,
-        "noEmit": true,
-        "jsx": "react-jsx",
-        "baseUrl": "src"
-    },
-    "include": ["src"]
+  "compilerOptions": {
+    "target": "es6",
```
Comment (MrKevinOConnell) [inline frontend/tsconfig.json:3]: 👍🏻

**Review by MrKevinOConnell — APPROVED** [review]
nice!
